baseURL = "https://compiler.team"
languageCode = "en-us"
title = "Compiler Team"
theme = "hugograyscale"

#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "Compiler Team"

[Author]
    name = "Bruno Flores"
    email = "bruno@brunoflores.com.br"

[Social]
    twitter = ""
